export const posts = [
  { type: 'image', src: 'assets/images/1.jpg', alt: '', title: 'pictures', link: '#me', views: 11 },
  { type: 'video', src: 'assets/videos/1.mp4', title: 'videos', link: '#me', views: 110 },
  { type: 'image', src: 'assets/images/2.jpg', alt: '', title: 'pictures', link: '#me', views: 1 },
  { type: 'image', src: 'assets/images/3.jpg', alt: '', title: 'pictures', link: '#me', views: 13 },
  { type: 'audio', src: 'assets/audios/1.mp3', title: 'audios', link: '#me', views: 11 },
  { type: 'image', src: 'assets/images/4.jpg', alt: '', title: 'pictures', link: '#me', views: 156 },
  { type: 'image', src: 'assets/images/5.jpg', alt: '', title: 'pictures', link: '#me', views: 16 },
  { type: 'video', src: 'assets/videos/2.mp4', title: 'videos', link: '#me', views: 1 },
  { type: 'image', src: 'assets/images/6.jpg', alt: '', title: 'pictures', link: '#me', views: 110 },
  { type: 'image', src: 'assets/images/7.jpg', alt: '', title: 'pictures', link: '#me', views: 61 },
  { type: 'audio', src: 'assets/audios/2.mp3', title: 'audios', link: '#me', views: 15 },
  { type: 'image', src: 'assets/images/8.jpg', alt: '', title: 'pictures', link: '#me', views: 31 },
  { type: 'image', src: 'assets/images/9.jpg', alt: '', title: 'pictures', link: '#me', views: 51 },
  { type: 'video', src: 'assets/videos/3.mp4', title: 'videos', link: '#me', views: 11 },
  { type: 'image', src: 'assets/images/10.jpg', alt: '', title: 'pictures', link: '#me', views: 113 },
  { type: 'audio', src: 'assets/audios/3.mp3', title: 'audios', link: '#me', views: 11 },
  { type: 'image', src: 'assets/images/11.jpg', alt: '', title: 'pictures', link: '#me', views: 11 },
]
