export const posts = [
  { type: 'image', src: 'assets/images/1.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'video', src: 'assets/videos/1.mp4', title: 'videos', link: '#me' },
  { type: 'image', src: 'assets/images/2.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'image', src: 'assets/images/3.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'audio', src: 'assets/audios/1.mp3', title: 'audios', link: '#me' },
  { type: 'image', src: 'assets/images/4.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'image', src: 'assets/images/5.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'video', src: 'assets/videos/2.mp4', title: 'videos', link: '#me' },
  { type: 'image', src: 'assets/images/6.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'image', src: 'assets/images/7.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'audio', src: 'assets/audios/2.mp3', title: 'audios', link: '#me' },
  { type: 'image', src: 'assets/images/8.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'image', src: 'assets/images/9.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'video', src: 'assets/videos/3.mp4', title: 'videos', link: '#me' },
  { type: 'image', src: 'assets/images/10.jpg', alt: '', title: 'pictures', link: '#me' },
  { type: 'audio', src: 'assets/audios/3.mp3', title: 'audios', link: '#me' },
  { type: 'image', src: 'assets/images/11.jpg', alt: '', title: 'pictures', link: '#me' },
]
